import Navbar from "@/components/Header/Navbar";
import AuthProvider from "@/providers/AuthProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-blue-50 to-indigo-100`}
      >
        <AuthProvider>
          <AntdRegistry>
            <Toaster />
            <div className="container mx-auto">
              <Navbar />
              {children}
            </div>
          </AntdRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
